language: android

dist: trusty

android:
  components:
  - tools
  - build-tools-28.0.3
  - android-28

before_install:
- openssl aes-256-cbc -K $encrypted_0a37c10e9e19_key -iv $encrypted_0a37c10e9e19_iv -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar

install:
- bundle install

script:
- "./gradlew clean assembleGreenstandDebug"
