name: Release Beta

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:
#    inputs:
#      environment:
#        description: 'git-tag'
#        required: true

jobs:
  release:
    name: Release to firebase beta
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: 'echo FIREBASE_TOKEN="$FIREBASE_TOKEN" > fastlane/fastlane.env'
      shell: bash
      env:
        FIREBASE_TOKEN: ${{secrets.FIREBASE_TOKEN}}
    - run: 'echo s3_dev_identity_pool_id=$S3_TEST_IDENTITY_POOL_ID > treetracker.keys.properties' 
      shell: bash
      env:
        S3_TEST_IDENTITY_POOL_ID: ${{secrets.S3_TEST_IDENTITY_POOL_ID}}
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6
    - name: Install bundle
      run: |
        gem install bundler
        bundle install
    - name: Set up git
      run: |
        git config --local user.email "automation@treetracker.org"
        git config --local user.name "Treetracker Automation"
    - name: Set up keys
      run: |
        echo s3_dev_identity_pool_id=$S3_TEST_IDENTITY_POOL_ID > treetracker.keys.properties
        echo FIREBASE_TOKEN=$FIREBASE_TOKEN > fastlane/fastlane.env
        cat fastlane/fastlane.env
        ls
    - name: Run fastlane
      run: |
        bundle exec fastlane firebase_beta
