name: Release Beta

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:
#    inputs:
#      environment:
#        description: 'git-tag'
#        required: true

jobs:
  release:
    name: Release to firebase beta
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: set up fastlane
      run: bundle install
  
