name: Release Beta

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'git-tag'
        required: true

jobs:
  check:
    name: test and assemble
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Generate dummy property file
        run: |
          echo "#Treetracker API Keys
          treetracker_client_id=dummy-id
          treetracker_client_secret=dummy-secret
          s3_dev_identity_pool_id=dummy-pool-id-dev
          s3_test_identity_pool_id=dummy-pool-id-test" > treetracker.keys.properties
      - name: Unit tests
        run: bash ./gradlew test --stacktrace
      - name: Build Debug APK
        run: bash ./gradlew :app:assembleDebug
      - name: Delete dummy property file
        run: rm treetracker.keys.properties


  release:
    name: Release to firebase beta
    needs: check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
#    - name: Set up keys
#      run: 'echo FIREBASE_TOKEN="$FIREBASE_TOKEN" > fastlane/fastlane.env'
#      shell: bash
#      env:
#        FIREBASE_TOKEN: ${{secrets.FIREBASE_TOKEN}}
    - name: Set up keys
      run: 'echo s3_dev_identity_pool_id=$S3_TEST_IDENTITY_POOL_ID > treetracker.keys.properties' 
      shell: bash
      env:
        S3_TEST_IDENTITY_POOL_ID: ${{secrets.S3_TEST_IDENTITY_POOL_ID}}
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6
    - name: Install bundle
      run: |
        gem install bundler
        bundle install
    - name: Set up git
      run: |
        git config --local user.email "automation@treetracker.org"
        git config --local user.name "Treetracker Automation"
    - name: Run fastlane
      run: |
        bundle exec fastlane firebase_beta
      env:
        FIREBASE_TOKEN: ${{secrets.FIREBASE_TOKEN}}
        SLACK_URL: ${{secrets.SLACK_URL}}
        SLACK_URL_QC: ${{secrets.SLACK_URL_QC}}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
